=== xuejiacore/IkeChat/IkeChat/src/main/resources/configuration.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--主配置-->
        <!ELEMENT configuration (config-name, init-main, cache-config?, init-param+, cluster-config?, extend-err-config?, response-filter?)>

        <!--配置名称-->
        <!ELEMENT config-name (#PCDATA)>
        <!--参数-->
        <!ELEMENT init-param (param-name,param-value)>
        <!ELEMENT param-name (#PCDATA)>
        <!ELEMENT param-value (#PCDATA)>

        <!--缓存配置-->
        <!ELEMENT cache-name (#PCDATA)>
        <!ELEMENT cache-class (#PCDATA)>
        <!ELEMENT file-path (#PCDATA)>
        <!ELEMENT driver (#PCDATA)>
        <!ELEMENT db-type (#PCDATA)>
        <!ELEMENT url (#PCDATA)>
        <!ELEMENT user (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT dbconfig (driver, db-type,url,user, password)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT cache-config (cache-name, cache-class,(file-path|dbconfig), description?)>

        <!--主参-->
        <!ELEMENT init-main (appid, appsecret, token)>
        <!ELEMENT appid (#PCDATA)>
        <!ELEMENT appsecret (#PCDATA)>
        <!ELEMENT token (#PCDATA)>

        <!--集群配置-->
        <!ELEMENT cluster-config (config-path, enable)>
        <!--错误扩展-->
        <!ELEMENT extend-err-config (config-path, enable)>

        <!ELEMENT enable (#PCDATA)>
        <!ELEMENT config-path (#PCDATA)>

        <!--微信响应处理器-->
        <!ELEMENT filter-name (#PCDATA)>
        <!ELEMENT filter-class (#PCDATA)>
        <!ELEMENT response-filter (filter-name, filter-class)>

=== xuejiacore/IkeChat/IkeChat/src/main/resources/default-chat-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE configuration SYSTEM "configuration.dtd">-->
<configuration>
    <!--配置名称-->
    <config-name>测试配置</config-name>

    <!--主公众号的配置-->
    <init-main>
        <appid>wx73e2dd423f007551</appid>
        <appsecret>d4624c36b6795d1d99dcf0547af5443d</appsecret>
        <token>zigui20120518</token>
    </init-main>

    <!--缓存配置-->
    <cache-config>
        <cache-name>FileCache</cache-name>
        <cache-class>org.ike.wechat.cache.DefaultFileCache</cache-class>
        <file-path>F:/Projects/IkeChat/token.conf</file-path>
        <description>文件方式</description>
    </cache-config>
    <!--数据库缓存方式
    <cache-config>
        <cache-name>DBCache</cache-name>
        <class-path>demo</class-path>
        <dbconfig>
            <driver></driver>
            <db-type></db-type>
            <url></url>
            <user></user>
            <password></password>
        </dbconfig>
        <description>数据库方式</description>
    </cache-config>
    -->

    <!--其他参数配置-->
    <init-param>
        <param-name>测试参数名称</param-name>
        <param-value>测试参数值</param-value>
    </init-param>

    <!--公众号群集配置(可选项)-->
    <cluster-config>
        <config-path>classpath:cluster-chat-config</config-path>
        <enable>false</enable>
    </cluster-config>

    <!--扩展的错误信息配置(可选项)-->
    <extend-err-config>
        <config-path>classpath:err-extention</config-path>
        <enable>true</enable>
    </extend-err-config>

    <response-filter>
        <filter-name>ResponseFilter</filter-name>
        <filter-class>org.ike.wechat.websupport.filter.ResponseListener</filter-class>
    </response-filter>
</configuration>
